#
# Azure Pipelines steps for building and testing create-react-app on Linux, Windows, and macOS.
#

steps:
  - script: |
      git config --global core.autocrlf false
      git config --global user.name "Create React App"
      git config --global user.email "cra@email.com"
    displayName: 'Initialize Git config settings'

  - checkout: self

  - bash: |
      set -x
      export y=$(yarn cache dir)
      mkdir -p $y
      curl https://createreactapp.blob.core.windows.net/cache/yarn-cache --output ${y}/yarn-cache.zip
      unzip -q ${y}/yarn-cache.zip -d ${y}/..
      rm ${y}/yarn-cache.zip
      echo $(yarn cache list)
    displayName: 'Seed yarn cache'

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: yarn --frozen-lockfile
    displayName: 'Install packages'
