#
# Azure Pipelines steps for building and testing create-react-app on Linux, Windows, and macOS.
#

steps:
  - script: git config --global core.autocrlf false    
  - checkout: self

  - bash: |
      npm config set registry https://pkgs.dev.azure.com/willsmythe/_packaging/create-react-app/npm/registry
      yarn config set registry https://pkgs.dev.azure.com/willsmythe/_packaging/create-react-app/npm/registry --verbose
      npm config set always-auth true
      
      t=~/.npmrc
      cat $t
      if [ "$OS" = "Windows_NT" ]; then
          t=$(echo $t | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')
      fi;
      echo "##vso[task.setvariable variable=npmrc_path]$t"
    env:
      ARTIFACTS_TOKEN: $(System.AccessToken)      

  - task: npmAuthenticate@0
    inputs:
      workingFile: $(npmrc_path)

  - bash: |
      cat $(npmrc_path)
      echo "-------------"
      npm config list
  
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: yarn --frozen-lockfile
    displayName: 'Install packages'
