#
# Azure Pipelines steps for building and testing create-react-app on Linux, Windows, and macOS.
#

steps:
  - script: git config --global core.autocrlf false    
  - checkout: self

  - bash: |
      npm config set registry https://pkgs.dev.azure.com/willsmythe/_packaging/create-react-app/npm/registry/
      npm config set always-auth true
      echo "##vso[task.setvariable variable=npmrc_path]~/.npmrc"

  - task: npmAuthenticate@0
    inputs:
      workingFile: $(npmrc_path)

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: yarn --frozen-lockfile
    displayName: 'Install packages'
