#
# Azure Pipelines steps for building and testing create-react-app on Linux, Windows, and macOS.
#

parameters:
  name: ''
  testScript: ''
  matrix:
    #LinuxNode8:    { VM_IMAGE: 'ubuntu-16.04',   NODE_VERSION: 8.x }
    LinuxNode10:   { VM_IMAGE: 'ubuntu-16.04',   NODE_VERSION: 10.x }
    #MacNode88:      { VM_IMAGE: 'macOS-10.13',    NODE_VERSION: 8.x }
    #MacNode810:     { VM_IMAGE: 'macOS-10.13',    NODE_VERSION: 10.x }
    WindowsNode8:  { VM_IMAGE: 'vs2017-win2016', NODE_VERSION: 8.x }
    WindowsNode10: { VM_IMAGE: 'vs2017-win2016', NODE_VERSION: 10.x }

jobs:
- job: ${{ parameters.name }}
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - script: |
      git config --global core.autocrlf false
      git config --global user.name "Create React App"
      git config --global user.email "cra@email.com"
    displayName: 'Initialize Git config settings'

  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: yarn --frozen-lockfile
    displayName: 'Install packages'

  - bash: ${{ parameters.testScript }}
    displayName: 'Run tests'