#
# Azure Pipelines steps for building and testing create-react-app on Linux, Windows, and macOS.
#

steps:
  - script: git config core.autocrlf false && git reset HEAD
    displayName: 'Ensure LF line endings'

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - bash: |
      yarn config set cache-folder $(Build.SourcesDirectory)/yarn-cache
    displayName: Change Yarn cache directory (Windows)
    condition: eq(variables['Agent.OS'], 'Windows_NT')

  - script: yarn --frozen-lockfile
    displayName: 'Install packages'
