#
# Azure Pipelines steps for building and testing create-react-app on Linux, Windows, and macOS.
#

steps:
  - script: git config --global core.autocrlf false
    
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
    displayName: 'Install Node.js'

  - script: yarn --frozen-lockfile
    displayName: 'Install packages'
